### ISSUE TITLE
php fatal error 

### ISSUE THREAD

**Issue by bnsave100** [kyo1337/CCEXTRAP#1]
`PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/CCEXTRAP/cc.class.php:122
Stack trace:
#0 /root/CCEXTRAP/cc.class.php(43): CC->Check('783736387614617...')
#1 /root/CCEXTRAP/run.php(14): CC->Execute()
#2 {main}
  thrown in /root/CCEXTRAP/cc.class.php on line 122`

**Comment by UNKNOW-afk717** [comment]
> PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/CCEXTRAP/cc.class.php:122
> Stack trace:
> #0 /root/CCEXTRAP/cc.class.php(43): CC->Check('783736387614617...')
> #1 /root/CCEXTRAP/run.php(14): CC->Execute()
> #2 {main}
>   thrown in /root/CCEXTRAP/cc.class.php on line 122

Same

**Comment by kyo1337** [comment]
ok, i will check this tool again

**Comment by darkhacknet** [comment]
> ok, i will check this tool again

im my case this is the error ! 

PHP Warning:  Attempt to read property "error" on null in /home/xxxxx/CCEXTRAP/cc.class.php on line 133

**Comment by darkhacknet** [comment]
> ok, i will check this tool again

Yeah it would be very good, I just raised another issue !

**Comment by hypixelalts** [comment]
> ok, i will check this tool again

any luck?
